### ISSUE TITLE
Not able to use this in angular 2

### ISSUE THREAD

**Issue by kushalsethi** [krtnio/angular-pretty-xml#4]
Can someone please explain how to use angular-pretty-xml in angular 2?

**Comment by kushalsethi** [comment]
Hello,
I want to pretty format xml in text area for my application. Can someone please explain how to use angular-pretty-xml for this in angular 2?

**Comment by v12** [comment]
Angular 2 does not have filters but [pipes](https://angular.io/docs/ts/latest/guide/pipes.html). Haven't had a look at it yet but it isn't difficult to make this module compatible with Angular 2.

**Comment by v12** [comment]
Here is an implementation of `prettyXML` pipe. You can use it in your project because I still need to figure out the best way to publish this.

```typescript
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({name: 'prettyXML'})
export class PrettyXMLPipe implements PipeTransform {
    static createShiftArr(step: number) {
        let space = '';
        if (isNaN(parseInt(step))) { // argument is string
            space = step;
        } else { // argument is integer
            for (let i = 0; i < step; i++) {
                space += ' ';
            }
        }

        let shift = ['\n']; // array of shifts

        for (let ix = 0; ix < 100; ix++) {
            shift.push(shift[ix] + space);
        }

        return shift;
    }

    transform(xml: string, indent: number) {
        if (isFinite(indent)) {
            if (indent !== 0) {
                indent = indent || 2;
            }
        } else if (typeof indent !== 'string') {
            indent = 2;
        }

        const arr = xml.replace(/>\s*</gm, '><')
            .replace(/</g, '~::~<')
            .replace(/\s*xmlns([=:])/g, '~::~xmlns$1')
            .split('~::~');

        let len = arr.length,
            inComment = false,
            depth = 0,
            string = '',
            shift = PrettyXMLPipe.createShiftArr(indent);

        for (let i = 0; i < len; i++) {
            // start comment or <![CDATA[...]]> or <!DOCTYPE //
            if (arr[i].indexOf('<!') !== -1) {
                string += shift[depth] + arr[i];
                inComment = true;

                // end comment or <![CDATA[...]]> //
                if (arr[i].indexOf('-->') !== -1 || arr[i].indexOf(']>') !== -1 ||
                    arr[i].indexOf('!DOCTYPE') !== -1) {
                    inComment = false;
                }
            } else if (arr[i].indexOf('-->') !== -1 || arr[i].indexOf(']>') !== -1) { // end comment  or <![CDATA[...]]> //
                string += arr[i];
                inComment = false;
            } else if (/^<\w/.test(arr[i - 1]) && /^<\/\w/.test(arr[i]) && // <elm></elm> //
                /^<[\w:\-\.,]+/.exec(arr[i - 1]) == /^<\/[\w:\-\.,]+/.exec(arr[i])[0].replace('/', '')) { // fixme WTF?
                string += arr[i];
                if (!inComment) {
                    depth--;
                }
            } else if (arr[i].search(/<\w/) !== -1 && arr[i].indexOf('</') === -1 && arr[i].indexOf('/>') === -1) { // <elm> //
                string += !inComment ? (shift[depth++] + arr[i]) : arr[i];
            } else if (arr[i].search(/<\w/) !== -1 && arr[i].indexOf('</') !== -1) { // <elm>...</elm> //
                string += !inComment ? shift[depth] + arr[i] : arr[i];
            } else if (arr[i].search(/<\//) > -1) { // </elm> //
                string += !inComment ? shift[--depth] + arr[i] : arr[i];
            } else if (arr[i].indexOf('/>') !== -1) { // <elm/> //
                string += !inComment ? shift[depth] + arr[i] : arr[i];
            } else if (arr[i].indexOf('<?') !== -1) { // <? xml ... ?> //
                string += shift[depth] + arr[i];
            } else if (arr[i].indexOf('xmlns:') !== -1 || arr[i].indexOf('xmlns=') !== -1) { // xmlns //
                string += shift[depth] + arr[i];
            } else {
                string += arr[i];
            }
        }

        return string.trim();
    }
}
```

**Comment by kushalsethi** [comment]
Thanks,
So I just need to apply it against my binding element as pipe.
Ex: <textarea id="comment">{{queryResult | prettyXML}}</textarea>

Is this correct?
Thanks! :)

**Comment by v12** [comment]
@kushalsethi yes, you're right 👍

**Comment by kushalsethi** [comment]
Thanks!

**Comment by Bhawna14** [comment]
Hi This piece of code doesnt work.
 else if (/^<\w/.test(arr[i - 1]) && /^<\/\w/.test(arr[i]) && // <elm></elm> //
                /^<[\w:\-\.,]+/.exec(arr[i - 1]) == /^<\/[\w:\-\.,]+/.exec(arr[i])[0].replace('/', '')) { // fixme WTF?
                string += arr[i];
and

 static createShiftArr(step: number) {
        let space = '';
        if (isNaN(parseInt(step))) { // argument is string
            space = step;

throws error

**Comment by Bhawna14** [comment]
i have to pretty print an xml in angular2

**Comment by v12** [comment]
@Bhawna14 you need to provide us with sample XML that fails

**Comment by Bhawna14** [comment]
@v12 Hi... Basically , its not about xml conversion.The code which you have given is throwing error for below lines.
1) if (isNaN(parseInt(step))) { 
            space = step;

error is type 'number is not assignable to type ;string'


And other piece of code is this.
2)} else if (/^<\w/.test(arr[i - 1]) && /^<\/\w/.test(arr[i]) && // <elm></elm> //
                /^<[\w:\-\.,]+/.exec(arr[i - 1]) == /^<\/[\w:\-\.,]+/.exec(arr[i])[0].replace('/', '')) 


just paste the code in any ts file and you will get the errors i am talking about.

Thank you :)

**Comment by v12** [comment]
@Bhawna14 yes, you're right. Below is the fixed version of the code
```typescript
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({name: 'prettyXML'})
export class PrettyXMLPipe implements PipeTransform {
  static createShiftArr(step: number | string) {
    let space = '';
    if (typeof step === 'number') { // argument is integer
      for (let i = 0; i < step; i++) {
        space += ' ';
      }
    } else { // argument is string
      space = step;
    }

    let shift = ['\n']; // array of shifts

    for (let ix = 0; ix < 100; ix++) {
      shift.push(shift[ix] + space);
    }

    return shift;
  }

  transform(xml: string, indent: number) {
    if (isFinite(indent)) {
      if (indent !== 0) {
        indent = indent || 2;
      }
    } else if (typeof indent !== 'string') {
      indent = 2;
    }

    const arr = xml.replace(/>\s*</gm, '><')
      .replace(/</g, '~::~<')
      .replace(/\s*xmlns([=:])/g, '~::~xmlns$1')
      .split('~::~');

    let len = arr.length,
      inComment = false,
      depth = 0,
      string = '',
      shift = PrettyXMLPipe.createShiftArr(indent);

    for (let i = 0; i < len; i++) {
      // start comment or <![CDATA[...]]> or <!DOCTYPE //
      if (arr[i].indexOf('<!') !== -1) {
        string += shift[depth] + arr[i];
        inComment = true;

        // end comment or <![CDATA[...]]> //
        if (arr[i].indexOf('-->') !== -1 || arr[i].indexOf(']>') !== -1 ||
          arr[i].indexOf('!DOCTYPE') !== -1) {
          inComment = false;
        }
      } else if (arr[i].indexOf('-->') !== -1 || arr[i].indexOf(']>') !== -1) { // end comment  or <![CDATA[...]]> //
        string += arr[i];
        inComment = false;
      } else if (/^<\w/.test(arr[i - 1]) && /^<\/\w/.test(arr[i]) && // <elm></elm> //
        /^<[\w:\-.,]+/.exec(arr[i - 1])[0] === /^<\/[\w:\-.,]+/.exec(arr[i])[0].replace('/', '')) {
        string += arr[i];
        if (!inComment) {
          depth--;
        }
      } else if (arr[i].search(/<\w/) !== -1 && arr[i].indexOf('</') === -1 && arr[i].indexOf('/>') === -1) { // <elm> //
        string += !inComment ? (shift[depth++] + arr[i]) : arr[i];
      } else if (arr[i].search(/<\w/) !== -1 && arr[i].indexOf('</') !== -1) { // <elm>...</elm> //
        string += !inComment ? shift[depth] + arr[i] : arr[i];
      } else if (arr[i].search(/<\//) > -1) { // </elm> //
        string += !inComment ? shift[--depth] + arr[i] : arr[i];
      } else if (arr[i].indexOf('/>') !== -1) { // <elm/> //
        string += !inComment ? shift[depth] + arr[i] : arr[i];
      } else if (arr[i].indexOf('<?') !== -1) { // <? xml ... ?> //
        string += shift[depth] + arr[i];
      } else if (arr[i].indexOf('xmlns:') !== -1 || arr[i].indexOf('xmlns=') !== -1) { // xmlns //
        string += shift[depth] + arr[i];
      } else {
        string += arr[i];
      }
    }

    return string.trim();
  }
}
```

**Comment by Bhawna14** [comment]
@v12 Thanks a tonn.. this works perfectly fine :)

**Comment by Bhawna14** [comment]
@v12 Hi... this is failing as ERROR TypeError: Cannot read property 'replace' of undefined..

can you please help me on this??

The xml used is 
<?xml version="1.0" encoding="UTF-8"?><ns19:EvtRspMsg xmlns:ns19="http://www.dhl.com/Express/CM/GenericEventRspMsg/v2"><Hdr Id="36101020-679c-46bc-8fcc-d12b0e5111d2" Ver="1.038" Dtm="2017-07-18T15:00:13" CorrId="b9dc3ef3-9390-43ab-9196-aa38f89c9281"><GI SrcUsr="jacostaf" SrcAppCd="OCNT" SrcSrvaCd="MTY" SrcFcCd="GTW"><TID Src="OCNT" TID="30a77f7f-9ab4-466d-8704-e36f58c772b5"/><TID Src="E2E" TID="4cad52e4-4016-4fbd-9c15-0d5547726505"/><TID Src="OCNT" TID="30a77f7f-9ab4-466d-8704-e36f58c772b5"/><TID Src="E2E" TID="4cad52e4-4016-4fbd-9c15-0d5547726505"/><TID Src="OCNT" TID="30a77f7f-9ab4-466d-8704-e36f58c772b5"/><TID Src="E2E" TID="4cad52e4-4016-4fbd-9c15-0d5547726505"/><TID Src="E2E" TID="4cad52e4-4016-4fbd-9c15-0d5547726505"/><TID Src="GIUS" TID="c70f26c2-9a78-41ee-b8e4-260ffa4d8385"/><TID Src="OCNT" TID="30a77f7f-9ab4-466d-8704-e36f58c772b5"/><TID Src="E2E" TID="4cad52e4-4016-4fbd-9c15-0d5547726505"/></GI><Sndr AppCd="ESB" AppVer="2.000" AppNm="ESB"/><Rcp AppCd="ESB" AppNm="OCNT"><GId Id="b9dc3ef3-9390-43ab-9196-aa38f89c9281" IdTp="RQMSGID"/></Rcp><Rcp AppCd="ESB" AppNm="OCNT"/></Hdr><Bd><BOEvt><GI CorrId="fa2ee44e-77c6-4bb4-af2b-db8f5a5113f4"/><PcsId>JD0030192613085296</PcsId><Evt><TyCd>PLCNT</TyCd><Dtm Off="-05:00">2017-07-18T15:00:06</Dtm><RecDtm Off="-05:00">2017-07-18T15:00:06</RecDtm><SDtm Off="-05:00">2017-07-18T15:00:13</SDtm><RCd>PLAHU</RCd><RDsc>Assigned to Handling Unit</RDsc><Rmk/><COpsFncId><OpsFncTyCd>OPS</OpsFncTyCd><OpsFncId>MTYGTW</OpsFncId><OpsFncIdAddDtEl><Cd>SrvaCd</Cd><Val>MTY</Val></OpsFncIdAddDtEl><OpsFncIdAddDtEl><Cd>FcCd</Cd><Val>GTW</Val></OpsFncIdAddDtEl><OpsFncIdAddDtEl><Cd>FcCd</Cd><Val>GTW</Val></OpsFncIdAddDtEl><OpsFncIdAddDtEl><Cd>SrvaCd</Cd><Val>MTY</Val></OpsFncIdAddDtEl><OpsFncIdAddDtEl><Cd>CtryCd</Cd><Val>MX</Val></OpsFncIdAddDtEl></COpsFncId><CIndvId>jacostaf</CIndvId><CMthCd>SCA</CMthCd><DatElGrp Cd="CommonGrp"><DatEl><Cd>NoPcs</Cd><Val>1</Val></DatEl><DatEl><Cd>PrntHUID</Cd><Val>H504304883</Val></DatEl></DatElGrp><DatElGrp Cd="CfgDat"><DatEl><Cd>Cat</Cd><Val>In Progress</Val></DatEl><DatEl><Cd>Cscd</Cd><Val>5</Val></DatEl></DatElGrp><GI CorrId="4b676ed5-3762-4eec-97af-58802b16ff1c"/></Evt></BOEvt></Bd><RspSt><Sev>0</Sev><MsgCIgd>400000</MsgCIgd><MsgClg/><Dsc>Message is valid</Dsc><DtlDsc/></RspSt><RspSt><Sev>0</Sev><MsgCIgd>000</MsgCIgd><MsgClg/><Dsc>Genius insert successful</Dsc><DtlDsc>Subject : Genius insert successful|Description : Genius insert successful</DtlDsc><RpBy CmptNm="EventServiceCBS.CheckpointCreateProvider"/></RspSt><RspSt><Sev>0</Sev><MsgCIgd>000</MsgCIgd><MsgClg/><Dsc>Genius insert successful</Dsc><DtlDsc>Subject : Genius insert successful|Description : Genius insert successful</DtlDsc><RpBy CmptNm="EventServiceCBS.EventCreateProvider"/></RspSt><RspSt><GI CorrId="36101020-679c-46bc-8fcc-d12b0e5111d2"/><Sev>10</Sev><MsgCIgd>100000</MsgCIgd><MsgClg>IPESB</MsgClg><Dsc>Service operation execution finished successfully</Dsc><DtlDsc>Service operation execution finished successfully</DtlDsc><RpBy AppNm="EventServiceCBS.Services:_eventCreateAndPublishCkPt"/></RspSt><RspSt><GI CorrId="36101020-679c-46bc-8fcc-d12b0e5111d2"/><Sev>10</Sev><MsgCIgd>100000</MsgCIgd><MsgClg>IPESB</MsgClg><Dsc>Service operation execution finished successfully</Dsc><DtlDsc>Service operation execution finished successfully</DtlDsc><RpBy AppNm="EventServiceCBS.Services:eventCreateAndPublishTopicString"/></RspSt></ns19:EvtRspMsg>

**Comment by Bhawna14** [comment]
@v12  can you please check this xml ? its failing to get formatted

**Comment by v12** [comment]
@Bhawna14 you have not supplied any XML 😄 Make sure you wrap it into ``` on both sides to preserve formatting (check out [this](https://guides.github.com/features/mastering-markdown/)).

**Comment by Bhawna14** [comment]
"<?xml version="1.0" encoding="UTF-8"?><ns23:EvtMsg xmlns:ns23="http://www.dhl.com/Express/CM/GenericEventMsg/v2" xmlns:ns5="http://www.dhl.com/Express/CM/CM_GenericRequest/v2"><Hdr Id="36101020-679c-46bc-8fcc-d12b0e5111d2" Ver="1.038" Dtm="2017-07-18T15:00:13" CorrId="b9dc3ef3-9390-43ab-9196-aa38f89c9281"><GI SrcUsr="jacostaf" SrcAppCd="OCNT" SrcSrvaCd="MTY" SrcFcCd="GTW"><TID Src="OCNT" TID="30a77f7f-9ab4-466d-8704-e36f58c772b5"/><TID Src="E2E" TID="4cad52e4-4016-4fbd-9c15-0d5547726505"/></GI><Sndr AppCd="ESB" AppVer="2.000" AppNm="ESB"/><Rcp AppCd="ESB" AppNm="OCNT"><GId Id="b9dc3ef3-9390-43ab-9196-aa38f89c9281" IdTp="RQMSGID"/></Rcp><Rcp AppCd="ESB" AppNm="OCNT"/></Hdr><Bd><BOEvt><GI CorrId="fa2ee44e-77c6-4bb4-af2b-db8f5a5113f4"/><PcsId>JD0030192613085296</PcsId><Evt><TyCd>PLCNT</TyCd><Dtm Off="-05:00">2017-07-18T15:00:06</Dtm><RecDtm Off="-05:00">2017-07-18T15:00:06</RecDtm><SDtm Off="-05:00">2017-07-18T15:00:13</SDtm><RCd>PLAHU</RCd><RDsc>Assigned to Handling Unit</RDsc><Rmk/><COpsFncId><OpsFncTyCd>OPS</OpsFncTyCd><OpsFncId>MTYGTW</OpsFncId><OpsFncIdAddDtEl><Cd>SrvaCd</Cd><Val>MTY</Val></OpsFncIdAddDtEl><OpsFncIdAddDtEl><Cd>FcCd</Cd><Val>GTW</Val></OpsFncIdAddDtEl><OpsFncIdAddDtEl><Cd>FcCd</Cd><Val>GTW</Val></OpsFncIdAddDtEl><OpsFncIdAddDtEl><Cd>SrvaCd</Cd><Val>MTY</Val></OpsFncIdAddDtEl><OpsFncIdAddDtEl><Cd>CtryCd</Cd><Val>MX</Val></OpsFncIdAddDtEl></COpsFncId><CIndvId>jacostaf</CIndvId><CMthCd>SCA</CMthCd><DatElGrp Cd="CommonGrp"><DatEl><Cd>NoPcs</Cd><Val>1</Val></DatEl><DatEl><Cd>PrntHUID</Cd><Val>H504304883</Val></DatEl></DatElGrp><DatElGrp Cd="CfgDat"><DatEl><Cd>Cat</Cd><Val>In Progress</Val></DatEl><DatEl><Cd>Cscd</Cd><Val>5</Val></DatEl></DatElGrp><GI CorrId="4b676ed5-3762-4eec-97af-58802b16ff1c"/></Evt></BOEvt></Bd></ns23:EvtMsg>
"

**Comment by Bhawna14** [comment]
Hi @v12 , i have pasted the XML.. this one is failing for above pipe.Could you please help me on this?

**Comment by v12** [comment]
@Bhawna14 please see my previous comment – put your code (snippet) into code block.

**Comment by lavanyakomarasamy** [comment]
@v12 Hi,  I am getting `"ERROR TypeError: xml.replace is not a function"`  for the following xml. Please help me to fix this.
`"responseMessage":["<urn:ivappProcess soapenv:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:urn=\"urn:vnm\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><response xsi:type=\"xsd:string\"><![CDATA[<nbaTransaction xsi:schemaLocation=\"urn:vnm.verizon.com/Schemas/NBParms NBParms.xsd\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns=\"urn:vnm.verizon.com/Schemas/NBParms\">\n  <requests xmlns=\"\">\n    <command>DEL</command>\n    <requestType>VNM_DELETE_SUBSCRIBER</requestType>\n    <groups>\n      <trails>\n        <tpaGigabitEthernet>\n          <rack>1</rack>\n          <shelf>2</shelf>\n          <slot>1</slot>\n          <port>7</port>\n          <circuitPack>5</circuitPack>\n        </tpaGigabitEthernet>\n        <attribute name=\"SUBSCRIPTION-ID\">ngpon2:225-20@BLT-E9-UAT1.verizon.com</attribute>\n        <attribute name=\"ACCOUNT-ID\">FLU0155755</attribute>\n        <attribute name=\"ORDER\">30037851</attribute>\n        <attribute name=\"TRANSACTION_ID\">1525835293727|3297888|249868316</attribute>\n        <attribute name=\"RESPONSEURL\">http://dqxsaczda14.ebiz.verizon.com:8003/ods/ODSSOAPResponseProxy</attribute>\n        <attribute name=\"TIMEOUT\">60000</attribute>\n        <attribute name=\"PRIORITY\">PRIORITY_4</attribute>\n        <attribute name=\"PCRF_DELETE\">Entry SubscriptionId=ngpon2:225-20@BLT-E9-UAT1.verizon.com,accountid=FLU0155755,ou=subscribers,dc=vzwireline,dc=com does not exist in the Directory Server</attribute>\n      </trails>\n    </groups>\n    <statuscode>V1006</statuscode>\n    <vnmdesc>[PROVISIONING](V1006) Entry SubscriptionId=ngpon2:225-20@BLT-E9-UAT1.verizon.com,accountid=FLU0155755,ou=subscribers,dc=vzwireline,dc=com does not exist in the Directory Server</vnmdesc>\n    <mne>\n      <tid>BALTPCRF</tid>\n    </mne>\n    <commands>\n      <install>Entry SubscriptionId=ngpon2:225-20@BLT-E9-UAT1.verizon.com,accountid=FLU0155755,ou=subscribers,dc=vzwireline,dc=com does not exist in the Directory Server\n\n[V1006] Entry SubscriptionId=ngpon2:225-20@BLT-E9-UAT1.verizon.com,accountid=FLU0155755,ou=subscribers,dc=vzwireline,dc=com does not exist in the Directory Server</install>\n    </commands>\n  </requests>\n  <statuscode xmlns=\"\">V1006</statuscode>\n  <vnmdesc xmlns=\"\">[PROVISIONING](V1006) Entry SubscriptionId=ngpon2:225-20@BLT-E9-UAT1.verizon.com,accountid=FLU0155755,ou=subscribers,dc=vzwireline,dc=com does not exist in the Directory Server</vnmdesc>\n</nbaTransaction>]]></response></urn:ivappProcess>"]
`

![image](https://user-images.githubusercontent.com/13619132/40168257-ac4be6a2-59e0-11e8-8398-6f7ef9e22695.png)

**Comment by v12** [comment]
@lavanyakomarasamy I think you're not passing XML string as an argument but an object instead.

In your case, I believe you need to use `yourVariableName.responseMessage[0]` since `responseMessage` is not a string but an array.

**Comment by lavanyakomarasamy** [comment]
Thank you so much  @v12 :+1: 
My one more requirement is I need to differentiate the tags in one color and the values in one color. Could you help me to achieve this?

**Comment by v12** [comment]
@lavanyakomarasamy as I already mentioned, [highlight.js](https://highlightjs.org/) does it - check it out.

**Comment by v12** [comment]
@lavanyakomarasamy ah, sorry, that was in another issue - https://github.com/krtnio/angular-pretty-xml/issues/6. Hope this helps 😉

**Comment by xts-velkumars** [comment]
> @Bhawna14 yes, you're right. Below is the fixed version of the code
> 
> ```ts
> import { Pipe, PipeTransform } from '@angular/core';
> 
> @Pipe({name: 'prettyXML'})
> export class PrettyXMLPipe implements PipeTransform {
>   static createShiftArr(step: number | string) {
>     let space = '';
>     if (typeof step === 'number') { // argument is integer
>       for (let i = 0; i < step; i++) {
>         space += ' ';
>       }
>     } else { // argument is string
>       space = step;
>     }
> 
>     let shift = ['\n']; // array of shifts
> 
>     for (let ix = 0; ix < 100; ix++) {
>       shift.push(shift[ix] + space);
>     }
> 
>     return shift;
>   }
> 
>   transform(xml: string, indent: number) {
>     if (isFinite(indent)) {
>       if (indent !== 0) {
>         indent = indent || 2;
>       }
>     } else if (typeof indent !== 'string') {
>       indent = 2;
>     }
> 
>     const arr = xml.replace(/>\s*</gm, '><')
>       .replace(/</g, '~::~<')
>       .replace(/\s*xmlns([=:])/g, '~::~xmlns$1')
>       .split('~::~');
> 
>     let len = arr.length,
>       inComment = false,
>       depth = 0,
>       string = '',
>       shift = PrettyXMLPipe.createShiftArr(indent);
> 
>     for (let i = 0; i < len; i++) {
>       // start comment or <![CDATA[...]]> or <!DOCTYPE //
>       if (arr[i].indexOf('<!') !== -1) {
>         string += shift[depth] + arr[i];
>         inComment = true;
> 
>         // end comment or <![CDATA[...]]> //
>         if (arr[i].indexOf('-->') !== -1 || arr[i].indexOf(']>') !== -1 ||
>           arr[i].indexOf('!DOCTYPE') !== -1) {
>           inComment = false;
>         }
>       } else if (arr[i].indexOf('-->') !== -1 || arr[i].indexOf(']>') !== -1) { // end comment  or <![CDATA[...]]> //
>         string += arr[i];
>         inComment = false;
>       } else if (/^<\w/.test(arr[i - 1]) && /^<\/\w/.test(arr[i]) && // <elm></elm> //
>         /^<[\w:\-.,]+/.exec(arr[i - 1])[0] === /^<\/[\w:\-.,]+/.exec(arr[i])[0].replace('/', '')) {
>         string += arr[i];
>         if (!inComment) {
>           depth--;
>         }
>       } else if (arr[i].search(/<\w/) !== -1 && arr[i].indexOf('</') === -1 && arr[i].indexOf('/>') === -1) { // <elm> //
>         string += !inComment ? (shift[depth++] + arr[i]) : arr[i];
>       } else if (arr[i].search(/<\w/) !== -1 && arr[i].indexOf('</') !== -1) { // <elm>...</elm> //
>         string += !inComment ? shift[depth] + arr[i] : arr[i];
>       } else if (arr[i].search(/<\//) > -1) { // </elm> //
>         string += !inComment ? shift[--depth] + arr[i] : arr[i];
>       } else if (arr[i].indexOf('/>') !== -1) { // <elm/> //
>         string += !inComment ? shift[depth] + arr[i] : arr[i];
>       } else if (arr[i].indexOf('<?') !== -1) { // <? xml ... ?> //
>         string += shift[depth] + arr[i];
>       } else if (arr[i].indexOf('xmlns:') !== -1 || arr[i].indexOf('xmlns=') !== -1) { // xmlns //
>         string += shift[depth] + arr[i];
>       } else {
>         string += arr[i];
>       }
>     }
> 
>     return string.trim();
>   }
> }
> ```

Its giving me an error like below 

![image](https://user-images.githubusercontent.com/13570225/195137101-e671edb5-06f2-43bd-a927-eec35c82e312.png)
